### ISSUE TITLE
mypy overload-overlap errors starting with mypy==1.11.0

### ISSUE THREAD

**Issue by dgilland** [dgilland/pydash#231] opened 2024-07-21 02:46 UTC
Starting with mypy==1.11.0, mypy throws the following errors:

```
src/pydash/objects.py:924:1: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
src/pydash/objects.py:962:1: error: Overloaded function signatures 1 and 3 overlap with incompatible return types  [overload-overlap]
src/pydash/objects.py:966:1: error: Overloaded function signatures 2 and 4 overlap with incompatible return types  [overload-overlap]
src/pydash/objects.py:1509:1: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
src/pydash/objects.py:1555:1: error: Overloaded function signatures 1 and 4 overlap with incompatible return types  [overload-overlap]
src/pydash/objects.py:1559:1: error: Overloaded function signatures 2 and 5 overlap with incompatible return types  [overload-overlap]
src/pydash/objects.py:1948:1: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
src/pydash/objects.py:2139:1: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
```

Affected functions are:

- `invert`
- `invert_by`
- `omit`
- `omit_by`
- `to_dict`
- `to_pairs`

@DeviousStoat any ideas for how to fix these?

**Comment by DeviousStoat** [comment] 2024-07-21 03:43
Yes, the problem is that a `Mapping` is also an `Iterable`. It is kind of okay because overloads are resolved in order but I guess it could fail to pick the proper type if the user specifies the type
```py
d: t.Iterable[str] = {"key": "value"}
x = invert(d)  #  x is reported as `dict[str, int]` whereas is should be `dict[str, str]`
```

One fix would be to use `Union[Sequence, Iterator]` instead of `Iterable` for the second overloads. It should still cover most of the cases. I opened a PR

**Closed** 2024-07-21 15:43 UTC
