### ISSUE TITLE
Comparators should handle None

### ISSUE THREAD

**Issue by dlopuch** [dgilland/pydash#126] opened 2019-06-19 20:07 UTC
Found on pydash 4.7.4

One of the things that made lodash great is its flexibility around null-handling... lodash seems to be opiniated that a null reference should just do something reasonable instead of throwing an exception.

In pydash, I noticed comparators are not null-safe. Consider:

```python
some_list = [{'a': 4}, {'a': 1}, {'b': 'Bb'}]
pydash.order_by(some_list, ['a'])
```

In lodash, this does something reasonable -- the 'b' item is put at the end.

In pydash, accessing `some_list[2]['a']` seems to internally resolve to None (great!), but then the comparator breaks trying to compare None to the other values:

```
.../python3.6/site-packages/pydash/collections.py in order_by(collection, keys, orders, reverse)
    673             return 0
    674
--> 675     return sorted(collection, key=cmp_to_key(comparison), reverse=reverse)
    676
    677

.../python3.6/site-packages/pydash/collections.py in comparison(left, right)
    667         # pylint: disable=useless-else-on-loop,missing-docstring
    668         for func, mult in comparers:
--> 669             result = _cmp(func(left), func(right))
    670             if result:
    671                 return mult * result

.../python3.6/site-packages/pydash/_compat.py in _cmp(a, b)
     84     izip = zip
     85
---> 86     def _cmp(a, b): return (a > b) - (a < b)
     87
     88

TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Expected Results: comparator-handling of None is handled in a reasonable way instead of crashing

**Comment by dgilland** [comment] 2019-07-02 01:43
Most of that in pydash is by design. However, I may be open to certain functions being less strict but, in general, exceptions from user supplied functions in pydash are left up to the user on how to handle them.

The primary reason being that, for example taking your example, having a `None` value in the list could indicate an error state where an exception like that means the list wasn't populate correctly (e.g. may there's a bug that produced a `None` value instead of an integer). If those cases were always ignored by pydash, then it would hide the potential error from the user which could make debugging harder. So pydash errs on not handling most exceptions so that the user can instead decide what to do in those cases.

**Comment by dlopuch** [comment] 2019-07-03 20:36
Thanks for the explanation. Didn't realize pydash has a different philosophy from lodash around strictness.

How about the explicit-None case though?  This creates the same error:

```
some_list = [{'a': 4}, {'a': 1}, {'a': None}]
pydash.order_by(some_list, ['a'])
```

I can understand the unspecified/implicit-None case, but this one seems like it should Just Work. One of the things I really like about pydash over relying on the built-ins or something more heavyweight like pandas is it just gets the job done quickly with minimal data munging. I think that "it always does something reasonable and never errors regardless of what you throw at it" philosophy is something that makes lodash really powerful.

**Comment by dgilland** [comment] 2019-07-05 02:25
For `order_by` specifically, I would be ok with it having the behavior you describe where `None` values are treated differently since that function is focused on sorting by key only (i.e. user isn't supply their own sort key function).

If you want to submit a PR for it, I'll merge it.

**Comment by IsabellaRO** [comment] 2020-06-26 11:21
Hi! I would like to work on this issue.

**Comment by dgilland** [comment] 2020-06-26 13:24
@dlopuch @IsabellaRO  This looks to be fixed by #137.

```python
>>> import pydash
>>> some_list = [{'a': 4}, {'a': 1}, {'b': 'Bb'}]
>>> pydash.order_by(some_list, ['a'])
[{'b': 'Bb'}, {'a': 1}, {'a': 4}]
>>> some_list = [{'a': 4}, {'a': 1}, {'a': None}]
>>> pydash.order_by(some_list, ['a'])
[{'a': None}, {'a': 1}, {'a': 4}]
```

**Comment by IsabellaRO** [comment] 2020-06-26 13:36
@dgilland Can you check with more than one occurency of None?
I got this: 

```python
>>> some_list = [{'a': 4}, {'a': 1}, {'a': None}, {'b': 1}, {'b': None}]
>>> pydash.order_by(some_list, ['a'])
[{'a': None}, {'b': 1}, {'b': None}, {'a': 1}, {'a': 4}]
>>> pydash.order_by(some_list, ['b'])
[{'a': 4}, {'a': 1}, {'a': None}, {'b': None}, {'b': 1}]
>>> pydash.order_by(some_list, ['b', 'a'])
[{'a': None}, {'b': None}, {'a': 1}, {'a': 4}, {'b': 1}]
```

**Comment by dgilland** [comment] 2020-06-26 15:42
@IsabellaRO Those look correct to me. `None` values are sorted first and without another field to sort by, the items with`None` are then sub-sorted by their position in the original list.

**Comment by IsabellaRO** [comment] 2020-06-26 19:41
@dgilland nice! So, is there anything left to do in this issue?

**Comment by dgilland** [comment] 2020-06-27 01:26
@IsabellaRO Nothing left to do for this issue so I'll go ahead and close it.

@dlopuch If you find something else, feel to re-open or submit a new issue. Thanks!

**Closed by dgilland** 2020-06-27 01:26 UTC
